### ISSUE TITLE
Crash on change theme

### ISSUE THREAD

**Issue by xmha97** [jetspiking/AndME#7]
This app is crashing on the change theme:

# Log:
```
java.lang.NullPointerException: Attempt to read from field 'com.dustinhendriks.andme.views.LauncherTilesFragment com.dustinhendriks.andme.views.LauncherTilesHomeFragment.mLauncherTilesFragment' on a null object reference in method 'void com.dustinhendriks.andme.MainActivity.notifyDataSetTilesUpdate()'
	at com.dustinhendriks.andme.MainActivity.notifyDataSetTilesUpdate(MainActivity.java:73)
	at com.dustinhendriks.andme.views.LauncherTilesFragment.loadData(LauncherTilesFragment.java:177)
	at com.dustinhendriks.andme.views.LauncherTilesFragment.onCreateView(LauncherTilesFragment.java:54)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2600)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:881)
	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
	at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2659)
	at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManagerImpl.java:2613)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:246)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:542)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:201)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1455)
	at android.app.Activity.performStart(Activity.java:8223)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3798)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2320)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8268)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)
```

**Comment by jetspiking** [comment]
Hi @xmha97. Thank you for reporting the issue. Could you explain the steps required for reproducing the issue?  With "theme" you refer to the accent color I presume? I hope to look into it Saturday or Sunday.

**Comment by jetspiking** [comment]
I published a new version today that also has changes to the settings screen. Could you verify whether the issue is present in the latest version?

Thanks in advance!

**Comment by xmha97** [comment]
> I published a new version today (2.0.2) that fixed another bug in the settings view. Could you verify whether the issue is present in the latest version?
> 
> Thanks in advance!

Hi, now I am using the new version (2.0.2)
The issue is present in the latest version.

https://user-images.githubusercontent.com/23485114/216176922-053bc216-c89d-4e0e-8911-44f5d27e30d9.mp4

**Comment by jetspiking** [comment]
@xmha97 Thank you for the video clearly this issue. At the moment this theme switch is not implemented, I never knew this could lead to a crash.

There are a few things that need to change in that case:
- Implement required event for changing light / dark mode
- Add images for light mode (at the moment white images are used for navigation), I will have to add black images.
- Background should automatically change to the lighter variant, while foreground and accent change to darker color. (FFFFFF-currentColor). Dark images used when background > FFFFFF/2, otherwise light

I'll try to implement this this month.

**Comment by xmha97** [comment]
Thanks, this is exactly what I want, adding the light theme and syncing the app theme with the OS theme.

**Comment by bassmeche** [comment]
@jetspiking using this on a color eink device running android 11. I was going to request the ability to change the color of the navigation buttons as a solid white background looks best. I think implementing what you mention will work as well for me, though.

**Comment by jetspiking** [comment]
@bassmeche Crash when changing theme bug has been resolved!
